title: Prepare to run a Code Club - Week 3
hero_image: images/banner.png
description: default-project-template description
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Introduction to Week 3
  - title: Creating a great club space
  - title: Club rules
  - title: Learning from success and failure
  - title: Certificates and motivation
  - title: Show and tell
  - title: Sharing young people’s work responsibly
  - title: Onwards and upwards!
  - title: Using additional hardware in your club
  - title: Peer mentoring
  - title: Including parents and family learning
  - title: Community and support
  - title: Welcome to the Code Club Community!
